HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch hist_ignore_dups
unsetopt beep

# Source Prezto and remove an alias from it
[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh
unalias rm

# Source FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Make ctrl-s work for reverse-i-search/i-search, from here: https://stackoverflow.com/a/25391867/870835
[[ $- == *i* ]] && stty -ixon

# Use neovim by default
export EDITOR='nvim'
export VISUAL='nvim'

# Set up ripgrep as fzf's backend
export FZF_DEFAULT_COMMAND='rg -g '!.git' --files --hidden --follow --ignore-file ~/.rgignore'

# Export path to include:
# node from NVM
# .local/bin (yarn)
# $HOME/.bin for my custom scripts
export PATH="$HOME/.local/bin:$HOME/.bin:$HOME/.nvm/versions/node/v10.15.3/bin:$PATH"

export KEYTIMEOUT=1

export PAGER="less -S"

# Go stuff
export GOPATH="$HOME/go"
export PATH="$GOPATH:$GOPATH/bin:$PATH"

# Set up aliases
source $HOME/.dotfiles/shell/aliases

# Support local modifications
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local

SPACESHIP_PROMPT_ORDER=(
  # time          # Time stamps section
  dir           # Current directory section
  git           # Git section (git_branch + git_status)
  # terraform     # Terraform workspace section
  # exec_time     # Execution time
  line_sep      # Line break
  # battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  # jobs          # Background jobs indicator
  # exit_code     # Exit code section
  char          # Prompt character
)

spaceship_vi_mode_enable
