HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch hist_ignore_dups
unsetopt beep

# Source Prezto and remove an alias from it
[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh
unalias rm

# Source FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Use neovim by default
export EDITOR='nvim'

# Set up ripgrep as fzf's backend
export FZF_DEFAULT_COMMAND='rg -g '!.git' --files --hidden --follow --ignore-file ~/.rgignore'

# Export path to include:
# node from NVM
# .local/bin (yarn)
# $HOME/.bin for my custom scripts
export PATH="$HOME/.local/bin:$HOME/.bin:$HOME/.nvm/versions/node/v10.15.3/bin:$PATH"
# Add yarn to path
export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

export KEYTIMEOUT=1

export PAGER="less -S"

# Set up aliases
source $HOME/.dotfiles/shell/aliases

# Support local modifications
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
