alias alr="source $HOME/.dotfiles/.bash_aliases"
alias ale="$EDITOR $HOME/.dotfiles/.bash_aliases"

alias a="cal"
alias g="git"
alias ga="git add -A"
alias gc="git commit"
alias gl="git log"
alias gs="git status"
alias ll="ls -aFhl"
alias ns="npm start"
alias nr="npm run"
alias tmn="tmux new -s main"
alias tma="tmux a"
alias mux="tmuxinator"
alias ip="curl ipecho.net/plain;echo"

alias bcodev="mosh brllnt@brllnt.co -- tmux attach"
alias yag="mosh chad@yaguara.co -- tmux attach"
alias rival="mosh brllnt@dev.therival.news -- tmux attach"
alias inforvellor="ssh ec2-user@ec2-54-191-19-166.us-west-2.compute.amazonaws.com"
alias chad="mosh chad@chadnickell.com -- tmux attach"
