alias alr="source $HOME/.dotfiles/.bash_aliases"
alias ale="$EDITOR $HOME/.dotfiles/.bash_aliases"

alias a="cal"
alias aria="aria2c"
alias au="sudo apt update && sudo apt upgrade -y"
alias c="clear"
alias g="git"
alias ga="git add -A"
alias gc="git commit"
alias gcod="git checkout develop"
alias gcom="git checkout master"
alias gcos="git checkout staging"
alias gd="git diff"
alias gl="git log"
alias gs="git status"
alias ip="curl ipecho.net/plain;echo"
alias k="kubectl"
alias kprod="k config use-context prod"
alias kstaging="k config use-context staging"
alias ll="ls -aFhl"
alias mosh='TERM=xterm-256color mosh'
alias mux="tmuxinator"
alias nr="npm run"
alias nrs="npm run --silent"
alias ns="npm start"
alias nsd="npm run start:debug"
alias nt="npm test"
alias pg="pgcli -D"
alias pgl="pgcli -D local"
alias pr="pull-request.sh"
alias r="ranger"
alias ranm="rm -rf node_modules && rnm && rm yarn.lock"
alias rc="source ranger"
alias remove-node-modules="find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +"
alias remove-lib="find . -name 'lib' -type d -prune -exec rm -rf '{}' +"
alias sc='echo "\x1B[?25h"'
alias ssh='TERM=xterm-256color ssh'
alias tf="terraform"
alias tm="tmux"
alias tma="tmux a"
alias tmn="tmux new -s main"
alias y="yarn"
alias ya="yarn add"
alias yi="yarn install"
alias yr="yarn run"
alias ys="yarn start"

alias rival="mosh brllnt@therival.news"
alias chad="mosh chad@chadnickell.com"
alias old_prod="ssh chad@104.236.24.3"
alias old_staging="ssh chad@45.55.200.167"

alias z='fasd_cd -d'

alias x='exit'
