let g:configDir = $HOME . '/.vim'

" {{{ Plugins and config
filetype off

call plug#begin(g:configDir.'/plugged')
    source $HOME/.dotfiles/vim/plugins.vimrc
    Plug 'Shougo/deoplete.nvim'
    Plug 'roxma/nvim-yarp'
    Plug 'roxma/vim-hug-neovim-rpc'
call plug#end()

source $HOME/.dotfiles/vim/general.vimrc

" deoplete
let g:deoplete#enable_at_startup = 1
" }}}

" {{{ Keymaps
nnoremap <leader>rc :so  ~/.vimrc<cr>
" }}}

" {{{ Hacks
if !has("gui_running")
    set t_Co=256
    set term=xterm-256color
endif
" }}}
