# vim: set fdm=marker fmr={{{,}}} fdl=0 ft=zsh:

# {{{ PATH
path+=$HOME/.bin
path+=$HOME/.local/bin

# Node 14.15.0
path+=$HOME/.nvm/versions/node/v14.15.4/bin

# Haskell
path+=$HOME/.cabal/bin
path+=$HOME/.ghcup/bin

# YVM
# export YVM_DIR=/home/chad/.yvm
# [ -r $YVM_DIR/yvm.sh ] && . $YVM_DIR/yvm.sh
path+=$HOME/.yvm/versions/v1.22.4/bin

# Yarn
path+=$HOME/.yarn/bin

# RVM
# path+=$HOME/.rvm/bin

typeset -U path

export PATH
# }}}

# Used in ranger
export TERMCMD='alacritty'

# Used in git aliases for code reviews
export REVIEW_BASE='master'

# Make escape work immediately
export KEYTIMEOUT=1

# Pager use less
export PAGER="less -S"

# Set up ripgrep as fzf's backend
export FZF_DEFAULT_OPTS='--bind alt-j:down,alt-k:up'
export FZF_TMUX=1

export DOTFILES="$HOME/.dotfiles"
