# vim: set fdm=marker fmr={{{,}}} fdl=0:

# {{{ ZSH Settings
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch hist_ignore_dups
unsetopt beep
# }}}

# {{{ Prezto
# Source Prezto and remove an alias from it
[ -f $HOME/.zprezto/init.zsh ] && source $HOME/.zprezto/init.zsh
unalias rm
# }}}

# {{{ Prompt
# {{{ Change prompt for SSH connections
if [ -n "$SSH_CLIENT" ] || [ -n "$SSH_TTY" ]; then
  SESSION_TYPE=remote/ssh
else
  case $(ps -o comm= -p $PPID) in
    sshd|*/sshd) SESSION_TYPE=remote/ssh;;
  esac
fi

if [ ! -z $SESSION_TYPE ]; then
    export PROMPT="[S] $PROMPT"
fi
# }}}

# Change prompt for inside ranger
if [ -n "$RANGER_LEVEL" ]; then export PS1="[R] $PS1"; fi
# }}}

# {{{ Configs
# {{{ FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Set up ripgrep as fzf's backend
export FZF_DEFAULT_OPTS='--bind alt-j:down,alt-k:up'
export FZF_TMUX=1

# Make ctrl-s work for reverse-i-search/i-search, from here: https://stackoverflow.com/a/25391867/870835
[[ $- == *i* ]] && stty -ixon
# }}}

# {{{  direnv
if [ -x "$(command -v direnv)" ]; then
    eval "$(direnv hook zsh)"
fi
# }}}

# NVM
# source /usr/share/nvm/init-nvm.sh
# source /home/chad/.nvm/nvm.sh
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Pager use less
export PAGER="less -S"

# Make escape work immediately
export KEYTIMEOUT=1

# Use neovim by default
export EDITOR='nvim'
export VISUAL='nvim'

# Used in git aliases for code reviews
export REVIEW_BASE='master'

# Used in ranger
export TERMCMD='alacritty'
# }}}

# {{{ Dotfiles
export DOTFILES="$HOME/.dotfiles"

# Set up aliases and functions
source $HOME/.dotfiles/generic/shell/aliases
for file in $HOME/.dotfiles/generic/shell/functions/*; do source $file; done
# }}}

# Support local modifications
[ -f $HOME/.zshrc.local ] && source $HOME/.zshrc.local
